[workspace]
authors = ["softwareentrepreneer <softwareentrepreneer+afterpython@gmail.com>"]
channels = ["conda-forge"]
name = "afterpython"
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
# NOTE: should match with setup-pixi in ci.yml
requires-pixi = ">=0.81.0,<0.82.0"
# exclude-newer = "14d"

[tasks]

[tasks.test-all]
depends-on = [
  { task = "test", environment = "py312" },
  { task = "test", environment = "py313" },
  { task = "test", environment = "py314" },
  # { task = "test", environment = "py315" },
]

[environments]
default = ["py312", "dev", "test", "optional"]
py312 = ["py312", "test", "optional"]
py313 = ["py313", "test", "optional"]
py314 = ["py314", "test", "optional"]

[dependencies]
gh = ">=2.102.0"

# `pixi config set pinning-strategy latest-up` removes the upper bound on the versions of the dependencies
[pypi-dependencies]
click = ">=8.5.0"
trogon = ">=0.6.0"
httpx2 = ">=2.13.1"
tomlkit = ">=0.15.1"
ruamel-yaml = ">=0.19.1"
gitpython = ">=3.2.0"
python-dotenv = ">=1.2.3"
pyproject-metadata = ">=0.12.1"
jupytext = ">=1.19.5"
mystmd = ">=1.11.0"
pdoc = ">=16.0.0"
ruff = ">=0.16.9"
prek = ">=0.5.4"
ty = ">=0.0.84"
git-cliff = ">=2.14.2"

[feature.optional.pypi-dependencies]
marimo = { version = ">=0.25.0", extras = ["recommended", "lsp"] }

[feature.dev.pypi-dependencies]
afterpython = { path = ".", editable = true }
notebook = ">=7.6.3"

[feature.test.pypi-dependencies]
afterpython = { path = ".", editable = true }
pytest = ">=9.1.1"
pytest-cov = ">=7.1.0"
pytest-mock = ">=3.16.0"
pytest-xdist = ">=3.8.0"
[feature.test.tasks]
test = "pytest -v -n auto"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.py314.dependencies]
python = "3.14.*"

# [feature.py315.dependencies]
# python = "3.15.*"
