[project]
name = "afterpython"
version = "0.3.19"
description = "CLI tool to streamline Python package maintenance and generate a dedicated project website"
license = "Apache-2.0"
authors = [
    { name = "Stephen Yau", email = "softwareentrepreneer+afterpython@gmail.com" },
]
readme = "README.md"
keywords = [
    "package-maintenance",
    "project-website",
    "static-site-generator",
    "developer-tools",
    "documentation",
    "cli-tool",
    "ci/cd",
    "mystmd",
    "semantic-release",
    "python-packaging",
]
classifiers = [
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Documentation",
    "Typing :: Typed",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    # "Programming Language :: Python :: 3.15",
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.5.0",
    "trogon>=0.6.0",
    "httpx2>=2.13.1",
    "tomlkit>=0.15.1",
    "ruamel-yaml>=0.19.1",
    "gitpython>=3.2.0",
    "python-dotenv>=1.2.3",
    "pyproject-metadata>=0.12.1",
    "jupytext>=1.19.5",
    "mystmd>=1.11.0",
    "pdoc>=16.0.0",
    "ruff>=0.16.9",
    "prek>=0.5.4",
    "ty>=0.0.84",
]

[project.optional-dependencies]
marimo = ["marimo[recommended,lsp]>=0.25.0"]

[project.urls]
homepage = "https://afterpython.afterpython.org"
repository = "https://github.com/AfterPythonOrg/afterpython"
documentation = "https://afterpython.afterpython.org/doc"

[project.scripts]
ap = "afterpython.main:run_cli"
pcu = "afterpython.main:run_pcu"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
# exclude-newer = "14 days"

[tool.uv.build-backend]
module-name = "afterpython"
module-root = "src"

[tool.ruff]
extend = "afterpython/ruff.toml"
