import os
import re
from pathlib import Path

import click

# e.g. "feat: add X", "fix(cli): handle Y", "refactor!: drop Z"
CONVENTIONAL_SUBJECT = re.compile(r"^(?P<type>[a-z][a-z0-9_-]*)(\([^()]*\))?!?: \S")
# messages generated by git itself, let them through as-is
GIT_GENERATED_PREFIXES = ("Merge ", 'Revert "', "fixup! ", "squash! ", "amend! ")
# `git commit -v` appends the diff below this line
SCISSORS = "------------------------ >8 ------------------------"
# prepare-commit-msg sources that already come with a message: -m/-F, merge, squash, --amend/-c
SOURCES_WITH_MESSAGE = ("message", "merge", "squash", "commit")


def _allowed_types(commit_types: dict, prefix: str) -> list[str]:
    width = max(len(t) for t in commit_types)
    return [f"{prefix}{t.ljust(width)}  {desc}" for t, desc in commit_types.items()]


def _template(commit_types: dict) -> list[str]:
    """Comment lines shown above git's own comments when the editor opens"""
    return [
        "# Format: <type>(<scope>): <description>, e.g. feat(cli): add --dry-run",
        "# Keep the title under 50 characters, 72 at most.",
        '# Add "!" before ":" for breaking changes, e.g. feat!: drop Python 3.10',
        "# Then a blank line and an optional body explaining what and why.",
        "#",
        "# Types (from afterpython/afterpython.toml [commit.types]):",
        *_allowed_types(commit_types, "#   "),
        "#",
        "# To commit without this format: SKIP=ap-commit git commit",
        "#",
    ]


def _add_template(message_file: Path, commit_types: dict):
    """Insert the template between the message (if any) and git's comments"""
    lines = message_file.read_text(encoding="utf-8").splitlines()
    first_comment = next(
        (i for i, line in enumerate(lines) if line.startswith("#")), len(lines)
    )
    # keep an empty first line for the subject
    head = lines[:first_comment] or [""]
    lines = head + _template(commit_types) + lines[first_comment:]
    message_file.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _subject(message: str) -> str:
    """Return the first non-comment, non-empty line of a commit message"""
    for line in message.splitlines():
        if SCISSORS in line:
            break
        if line.startswith("#") or not line.strip():
            continue
        return line.strip()
    return ""


@click.command("commit-msg", hidden=True)
@click.argument("message_file", type=click.Path(exists=True, path_type=Path))
@click.option(
    "--template",
    is_flag=True,
    help="Add the commit types to the message template instead of checking the message (prepare-commit-msg stage)",
)
@click.pass_context
def commit_msg(ctx, message_file: Path, template: bool):
    """Check a commit message against [commit.types] in afterpython.toml (used by the ap-commit hook)

    Without (or with an empty) [commit.types], any message is accepted.
    """
    from afterpython._io.toml import _from_tomlkit
    from afterpython.tools._afterpython import read_afterpython

    commit_types: dict = _from_tomlkit(read_afterpython().get("commit", {})).get(
        "types", {}
    )
    if template:
        # no template when the message is given already, or the check will report missing types
        source = os.environ.get("PRE_COMMIT_COMMIT_MSG_SOURCE", "")
        if commit_types and source not in SOURCES_WITH_MESSAGE:
            _add_template(message_file, commit_types)
        return

    # opted out: no (or an empty) [commit.types] section means no check
    if not commit_types:
        return

    subject = _subject(message_file.read_text(encoding="utf-8"))
    # empty messages are rejected by git itself
    if not subject or subject.startswith(GIT_GENERATED_PREFIXES):
        return

    match = CONVENTIONAL_SUBJECT.match(subject)
    if match and match.group("type") in commit_types:
        return

    if match:
        reason = f"unknown commit type '{match.group('type')}'"
    else:
        reason = (
            "commit message doesn't follow the format '<type>(<scope>): <description>'"
        )
    allowed = "\n".join(_allowed_types(commit_types, "  "))
    click.echo(
        f"❌ {reason}\n"
        f"   > {subject}\n\n"
        f"Allowed types (from afterpython/afterpython.toml [commit.types]):\n{allowed}\n\n"
        f"Your message is saved, edit and retry with: git commit -e -F {message_file}\n"
        f"To commit without this check:             SKIP=ap-commit git commit",
        err=True,
    )
    ctx.exit(1)
